version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smalfiles
  app:
    image: todo-app-docker.jar
    ports:
    - 9090:8080
    links:
    - mongodb